# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 222c52b31043ce0548b75d7a93a374c4fe8d044086104fbf1c586a3e18665d1e7a1e55f8c63e6a70f8340f839d32a097098d01d105c563fe45f9c5bfe6672260

test:
  secret_key_base: 634935e3d4cfabc9d034c11ff7322b7124fe098999803aac0d4e501d179e59deff9ff1319be28b7700631e680c26253d028d3cb05fbc7e11e554d275bed89107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
